
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzU4MDA4YWY5NzdlZTBiNTgzYjlhN2YiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJtdWhzdXByaWF6aXNAZ21haWwuY29tIiwiaWF0IjoxNjY2NzE1MDg5LCJleHAiOjE2NjY3MTUxMDR9.tnuIUWhrSfeBW8WWOBxUE97YqFtwtpjEl5emK4aApmQ
###
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "admin",
    "email": "muhsupriazis@gmail.com",
    "password": "admin",
    "confirm": "admin"
}

###
DELETE  http://localhost:5000/api/user/63569e8f5fbcf6926dca579e

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}
###
GET http://localhost:5000/api/auth/token

###
DELETE  http://localhost:5000/api/auth/logout

###
GET  http://localhost:5000/api/portfolios
###
POST   http://localhost:5000/api/portfolios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzU4MDA4YWY5NzdlZTBiNTgzYjlhN2YiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJtdWhzdXByaWF6aXNAZ21haWwuY29tIiwiaWF0IjoxNjY2NzExODc4LCJleHAiOjE2NjY3MTE4OTN9._d2FBNrIUwrtDP-9P__d8dblNrQbcoUMuP-iprgqhoQ

Content-Type: application/json

{
    "companyName": "dicoding",
    "description": "hello",
    "tools": ["expres", "vscode"],
    "github" : "muhsupri",
    "deploy": "muhsupri.com",
    "imgUrl": "muhsri.coms"
}
###
GET  http://localhost:5000/api/portfolios/6357351a2dbf32071b470b6e

###
PATCH http://localhost:5000/api/portfolios/6357351a2dbf32071b470b6e
Content-Type: application/json

{
    "companyName": "kampus",
    "description": "hello2"
}

###
DELETE http://localhost:5000/api/portfolios/635736acf7fd6629858a184b

###
GET  http://localhost:5000/api/blogs
###

###
GET http://localhost:5000/api/auth/token
###
POST   http://localhost:5000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzU4MDA4YWY5NzdlZTBiNTgzYjlhN2YiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJtdWhzdXByaWF6aXNAZ21haWwuY29tIiwiaWF0IjoxNjY2NzExOTYzLCJleHAiOjE2NjY3MTE5Nzh9.bBCSK4cht1nSR5A_z0PWtRz4_MJZbYAXPzc6wc6dWdk

Content-Type: application/json

{
    "title": "hello",
    "summary": "sumary",
    "slug": "slug",
    "author": "author",
    "body": "body"
}
###
GET  http://localhost:5000/api/blogs/6357ff329c9c83c8aa570ddb

###
PATCH http://localhost:5000/api/blogs/6357ff329c9c83c8aa570ddb
Content-Type: application/json

{
    "title": "hello1",
    "summary": "sumary1",
    "slug": "slug1",
    "author": "author1",
    "body": "body1"
}

###
DELETE http://localhost:5000/api/blogs/6357ff329c9c83c8aa570ddb


###
GET  http://localhost:5000/api/certificates
###

###
GET http://localhost:5000/api/auth/token
###
POST   http://localhost:5000/api/certificates

Content-Type: application/json

{
    "name": "name",
    "description": "sumary",
    "github": "slug",
    "author": "author",
    "body": "body"
}
###
GET  http://localhost:5000/api/certificates/6357ff329c9c83c8aa570ddb

###
PATCH http://localhost:5000/api/certificates/6357ff329c9c83c8aa570ddb
Content-Type: application/json

{
    "title": "hello1",
    "summary": "sumary1",
    "slug": "slug1",
    "author": "author1",
    "body": "body1"
}

###
DELETE http://localhost:5000/api/certificates/6357ff329c9c83c8aa570ddb
